### PR TITLE
GCW-2132 # Search_module and search_organisations removed and added to goodcity-lib

### PR DESCRIPTION
**Pull request by abulsayyad123**
Hi Team,
This is PR for New User Sign up feature. https://jira.crossroads.org.hk/browse/GCW-2132.

Search Organisation and Search Module has been common in both Browse and Stock. So has been added in Goodcity-lib and removed from this repo.
Please review this PR and let me know if any change is required.

Thanks

### CODE REVIEW

**Comment by Darshan-Chauhan** [comment]
@namrataukirde , the code climate change is ridiculous. Should we drop code-climate for code-coverage and use other service??

CC: @abulsayyad123

**Comment by abulsayyad123** [comment]
Total-coverage has gone down because there are test cases that are dependent on search_organisation and search_module controllers which have been moved to goodcity-lib. Once  these controllers  will be merged in master of goodcity-lib. These failing test-case will get covered from goodcity-lib.

**Comment by Darshan-Chauhan** [comment]
@abulsayyad123 , what's the status on this?

**Comment by namrataukirde** [comment]
@abulsayyad123 If this PR is not needed then can you close this? Else what's status of this PR ?

**Comment by abulsayyad123** [comment]
Closing this PR as these files have dependency in there respective apps i.e Stock and Browse.

**Pull request closed without merging**
