### PR TITLE
Discussion: Adding JSDoc

### PR DESCRIPTION
**Pull request by patrixr**
Hey team, 

I've been doing this in parallel of my task, I've extracted it into its own branch for you to test and let me know what you think.

The idea is to use JSDOC comments to keep track of everything. A lot of them were pre-existing so overall it was pretty easy to just tweak them a bit to get a decent setup.

Note: I've only documented the app partially here and there to get a feel for it.

Testing:

```bash
$> git fetch && git checkout jsdoc
$> yarn install  # to add the jsdoc dependency (node >= 8.15)
$> yarn document # generates a 'documentation' folder
$> open documentation/index.html # view the documentation in your browser
```
Questions in mind:
- [ ] Is this a good way of keeping track of existing code
- [ ] Does it clutter the code too much ?

If you guys like this idea we can merge it, otherwise we can just discard the PR

### CODE REVIEW

**Comment by patrixr** [comment]
> ... i guess no need for docs on internal functions but more of the external APIs that our apps will use

I mostly documented the "reusable" parts of the app, meaning Services/Components as if they were external.
The best way to test is to pull the branch and generate the doc locally (takes about a second)

**Comment by abhinav098** [comment]
Nice plugin documentation looks awesome.

**Comment by namrataukirde** [comment]
PR looks good to me. I fetched branch on my local and checked generated documentation and we all checked docs on my local machine. It looks nice. Well done. 👏 👍

**Comment by namrataukirde** [comment]
It will be good to add the following to lines to our repo readme. :)

$> yarn document # generates a 'documentation' folder
$> open documentation/index.html # view the documentation in your browser

**Comment by patrixr** [comment]
Thanks for trying it out team, I'll add the readme instructions and merge 👍

**Pull request merged**
